In [1]:
import json
import os
import time
from google import genai
from google.genai import types
import datetime
import asyncio


with open('keys.json', 'r') as file:
    keys = json.load(file)

### Grounding the search for specific hardware EOS.

In [ ]:
hardware_name = "iPhone 7 Plus"
prompt = f"What is the Hardware/Software End-of-Support (EOS) for '{hardware_name}'. Check offical sources first and then other websites and concur within that the EOS date is factual, always choose the official sources as much as possible. Also, based on the number of sources that agree with the EOS date, give a best guess confidence score (from 0-1, two decimal points). If there are no sources and you are unable to safely determine the date, return 'No EOS found'. Strictly return in this JSON format for example: 'Software':{hardware_name}, 'EOS Date': 'YYYY-MM-DD'/'No EOS found', 'confidence': 0.86. DO NOT return any other text or explanation, just the JSON object with the keys 'Software', 'EOS Date', and 'confidence'."
prompt

"What is the Hardware/Software End-of-Support (EOS) for 'Alcatel OmniSwitch 6850-24'. Check offical sources first and then other websites and concur within that the EOS date is factual, always choose the official sources as much as possible. Also, based on the number of sources that agree with the EOS date, give a best guess confidence score (from 0-1, two decimal points). If there are no sources and you are unable to safely determine the date, return 'No EOS found'. Strictly return in this JSON format for example: 'Software':Alcatel OmniSwitch 6850-24, 'EOS Date': 'YYYY-MM-DD'/'No EOS found', 'confidence': 0.86. DO NOT return any other text or explanation, just the JSON object with the keys 'Software', 'EOS Date', and 'confidence'."

In [2]:
with open('prompt.txt', 'r') as pmt_file:
    instruct = pmt_file.read()

In [43]:
def client_setup():
    client = genai.Client(api_key=keys['GEMINI_API_KEY'])

    # Set up the google search tool for the client.
    scraper_client = types.Tool(google_search=types.GoogleSearch())
    config = types.GenerateContentConfig(
        tools=[scraper_client],
        thinking_config=types.ThinkingConfig(thinking_budget=-1),
        temperature = 0.2,
)
    return client, config

### Processing the HW File

In [2]:
import pandas as pd
import time
from classes import Helper, Cleaner, Processing

In [ ]:
# read the file in 
from classes import Helper

df = Helper.preprocess('SWandHW.xlsx', sheet='Sheet1')

Starting Preprocessing...
Asset list read in 25.3s
-----------------------------------

In [6]:
omnii_sw = Cleaner.clean_text_to_unique(df["Software Version"])
omnii_sw

array(['ekm 1.10', 'mobimed 4.8.1', '7zip 19.00',
       'google chrome 115.0.5790.102', 'splunk universal fowarder 9.0.2',
       'windows server 2016', 'sql server 2016', 'ekm agent 8.4.2',
       'sql server management studio v19.1', 'jboss eap 7.3',
       'java 8 jre v371', 'ibm websphere mq explorer 9.3.2',
       'omnii gateway v1.1.0', 'display terminal 1.2.1',
       'windows server 2019', 'audit app 1.1.1',
       'solarwinds sem agent 2023.2.1', 'powerbi 2.93.641.0',
       'omnii gateway v1.0.0', 'sem 2023.2.1', 'ibm isam aac 10.0.2',
       'ibm isam rp 10.0.2', 'telemedicine 1.0.0'], dtype=object)

### Gemini API and JSON parsing

In [ ]:
import asyncio
from classes import Helper, Cleaner, Processing

def error_cache(results, eos_list):
    """
    Caches the results and eos_list for items that failed to process.
    """
    success, unsuccess = [], []
    for i, result in enumerate(results):
        if result is not None:
            success.append(result)
        else:
            unsuccess.append(eos_list[i])  # This mapping is always correct
    return success, unsuccess

async def process_line(string, client, config):
    print(f"Processing item: {string}")
    try:
        await asyncio.sleep(2)  # Sleep to avoid hitting rate limits
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=instruct + ' ' + string,
            config=config
        )
        return Helper.parse_llm_json(response.text) # includes throwing none in here as well
    except Exception as e:
        print(f"Error processing {string}: {e}")
        return None # need to add some handling here to log if needed. 

async def main(eos_list):
    client, config = client_setup()
    tasks = [process_line(item, client, config) for item in eos_list]
    results = await asyncio.gather(*tasks)

    # error caching for failed API calls or bad responses
    success, unsuccess = error_cache(results, eos_list)

    print(f"Successfully processed {len(success)} items.")
    
    # Add a retry limit if needed
    retry_limit = 3
    retry_count = 0

    while unsuccess and retry_count < retry_limit:
        print(f"Retrying {len(unsuccess)} items...")
        retry_tasks = [process_line(item, client, config) for item in unsuccess]
        retry_results = await asyncio.gather(*retry_tasks)
        retry_success, unsuccess = error_cache(retry_results, unsuccess)
        
        # add to main success list
        success.extend(retry_success)

        retry_count += 1
        if unsuccess:
            print(f"Retry {retry_count} failed for {len(unsuccess)} items.")
    
    return success, unsuccess

async def run_async(lst):
    print("Starting async processing...")
    # add time start
    start_time = time.time()
    results, failed_items = await main(lst)
    # add time end
    elapsed = time.time() - start_time  # Calculate elapsed time
    print(f"Time taken: {elapsed:.2f} seconds")  # Print elapsed time
    print("Async processing completed.")
    return results, failed_items 

# Run the async function, change this for the script. 
results, failed_items = await run_async(omnii_sw[2:7])
results

Starting async processing...
Processing item: 7zip 19.00
Processing item: google chrome 115.0.5790.102
Processing item: splunk universal fowarder 9.0.2
Processing item: windows server 2016
Processing item: sql server 2016
Successfully processed 5 items.
Time taken: 92.93 seconds
Async processing completed.

([{'Name': '7-Zip 19.00',
   'Summary': '7-Zip operates on a rolling support model, meaning that support and updates are only provided for the latest version. Older versions, including 7-Zip 19.00, do not receive ongoing updates or bug fixes once newer versions are released.',
   'Hardware/Software': 'Software',
   'Support Model': 'Rolling',
   'EOS Date': None,
   'Support Tiers': [],
   'Source URLs': ['https://www.7-zip.org/support.html',
    'https://sourceforge.net/p/sevenzip/discussion/45797/thread/45d13460/',
    'https://sourceforge.net/p/sevenzip/discussion/45797/thread/45d13460/?limit=25#138b',
    'https://www.7-zip.org/faq.html',
    'https://www.7-zip.org/history.txt',
    'https://sourceforge.net/p/sevenzip/discussion/45797/thread/08277218/'],
   'Confidence': 1.0},
  {'Name': 'Google Chrome 115.0.5790.102',
   'Summary': 'Google Chrome operates on a rapid release cycle, with new major versions released approximately every four weeks. Only the latest major version receives ongoing feature, bug, and security updates, effectively making support for older versions rolling. The Extended stable channel for enterprises receives updates every eight weeks.',
   'Hardware/Software': 'Software',
   'Support Model': 'Rolling',
   'EOS Date': None,
   'Support Tiers': [],
   'Source URLs': ['https://chromium.googlesource.com/chromium/src/+/main/docs/release_cycle.md',
    'https://support.google.com/chrome/a/answer/1021666?hl=en',
    'https://www.chromium.org/developers/calendar/',
    'https://endoflife.date/chrome',
    'https://chromereleases.googleblog.com/2023/07/stable-channel-update-for-desktop_20.html'],
   'Confidence': 1.0},
  {'Name': 'Splunk Universal Forwarder 9.0.2',
   'Summary': 'Splunk Universal Forwarder versions 7.0 and onward are supported for a total of sixty (60) months from their release date, with different support tiers during this period.',
   'Hardware/Software': 'Software',
   'Support Model': 'Version-Based',
   'EOS Date': '2027-06-14',
   'Support Tiers': [{'Tier': 'Mainstream Support', 'EndDate': '2024-06-14'},
    {'Tier': 'Limited Support (P3 level)', 'EndDate': '2027-06-14'}],
   'Source URLs': ['https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHQLxUdBmm-PGqr_ORlVHg_DNXxc1TtkCPvVzryN9ldjwPV8LEY9X3ZYWUcGUSbczYvtZt7ChZpW3W21fa2wewGW6EB6drlw97TKV3QHJ8DcjpvKcsWfQBambXE-tWicqzrtYVWBxPDwBn9deIa1NEDbS5J05AyoaqcLumpk4wnTQ==',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGlIMhTut2BDn9xdTgGSMWwLqB7H0G3-xxPM9WGgXLXMrvHH1RphoOC7xm0c2ghBiZ-qgRUO0Xmw5heHNFYE4YxapS1Jh-q_lwObHkh9GtEBSx0sK6hVZZnMHSFsecTgnS1vYYFJLb4eiHS9TuJFhoXJg-Ken7dPSqQRlhbIQDznGJ5WnC1XLU=='],
   'Confidence': 1.0},
  {'Name': 'Windows Server 2016',
   'Summary': 'Windows Server 2016 follows a Fixed Lifecycle Policy, with mainstream support ending on January 11, 2022, and extended support, which includes security updates, concluding on January 12, 2027.',
   'Hardware/Software': 'Software',
   'Support Model': 'Fixed',
   'EOS Date': '2027-01-12',
   'Support Tiers': [{'Tier': 'Mainstream Support', 'EndDate': '2022-01-11'},
    {'Tier': 'Extended Support', 'EndDate': '2027-01-12'}],
   'Source URLs': ['https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG7JUSgLIbdr80Y6F3hvpQ7oaNgRtZcgdzD65Tyzx2bPW7g9c3_Mfr5_i5ptm2WWiupxbOdAtOGKz_4zH31cyzl4tkclv4iXzaRZ2x1s6VXwewlkmMaaSt-MkA2ssuPGh57GSQOXc9dWORzknxdOShktH8Q3-Y782UqmNnVU0621kG6KFuvPkSD2KSnvoqBW4zb7OWiJc4=',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGOpQuTKGqO9Cl3JGVhCfkOEVcQy-QBbue7ltTJur-u5vn4wPl1OXNadfnrn6kWZ4Ur7JdT5_Ml-oqiswFRfCqb2PrOs9ibCgEeOxVTuOuK-3yCCDTV58JoqxTHm2GxcCiHD_ufkbJvse9LpAjJzjtuofCnZcaKXohtaDDltip-',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFrVDjg8E2VDA0Dbbf4dus3Zo5dAqY3jUAx09T-6jMqnBcsoVFURKxoYp-PYDhlxZn_a4w7WLPhkceIt2zkRJ-CHALXauSZ6ejd16uAC3jlSx8PDAWfF0vzWlBRIgJb93cm1DAb4stvth-CrrHO2MqqnSh-FNtaZQ==',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGjPrgTCdz65if-EH-UgGQD2qgxX1BSYKgNHs9Ra_qzFSChvonjKPyLnsWQ0AXQZuebaCBRChcecEHzgtQvQHNLFGJ03lErAcuhM6APLTks3reI4Zo50eBjXHzH-ifKMYOuW0LFR7tX7lrYiScpCIHTD_PL0LMPIleP2jVr7ss=',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEUyL0U7j8vAZ6l4SSz35AeEZqdKJk2dCmMF5K3dhQkJ-mA7bo_jVdZwhrh1H399q5vrgmHKwDAVK7v47IJHywgOlnji75SFQ5cfCTN6b5rpfMvnti2Lvg1JiDsmvf68QrzC-sIv6Artyw-iofMfSxnECQFqMKuSwbuyNxw4wpmcXZz-wuBh5Vp73TFWb6Cz749VdEByS5gJzocqXU=',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGswhQe0Zt7Y4GrJ_HgXC7ma2tB1s0ssdecQu4ZOc6TurjsdZjv0ZcLdWyojsxSjuzppvbRXx9E-pwHFZdqQNZUuGpUwYI6AIPZes04eIjcj0mH2tjhjP3uYBbkpA-yBf0RMSFtj-7aguud69JYMZNaUJp7mAk=',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEospAF45x1lgP_7J2pq0MjzncE1ffCURjLnv3bsi8hCHUAKl-IwklxBYMRhqLEGafJ3wnT6uCedtsOzjjKfQ_gCGgdE1vS-XeDicjaW9IGFMXOsF2Svye_UbwsZY5fz00_aG6FUsotaW0vJhckFMpxmXz6fQ==',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEDSSUBJBmqofoMHthiwo6TvLlzRDYS8z5HV-ysuJ6l6pUqHHBIuoAR4bjUMkosulrZPDMgkL2zSlT7QLebxhUBuZDIneUor5AZcp8gmxrEqhV8bpN8Ww0y0buxPGxfgGAiX7HfxtlG_hDzsGuw-mBToB4LYfwBVRIOHERJBmHY0lUb',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGDhK9XHlA1qQhkqul9yXWG2liUMVDl9IT7HMEIYM6-rBgK_Bo_1B6_Hlx1lnKQzBPsmDt5QvzVz0A-gXIOmVIPnWLVh_MDHBB1svhrc69fhKe_wskolzebdKrrBhU8G-S_PzSU-HaByfGCaez5USYtfDC7g_WdPnB709BhFNk4Ty5dttKjBNUsi5G_VdW-Dfv4IPxPSN9AfzXCBWNrBbteUSLfkPnj3w=',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGd_qWxCUfox1yBljc1xK6Owua_-6f0YLBwIXjc8SoHrO-rK16wqudzu9Ul_4CP0317XFaQYQLar4xPPCwNPtPL7Puy5PcUW_MfPeQT5T_Ok2iH3CSviPCdYP8T3kXI4xIh8Uu5mA==',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFuGtJ0jJi-KOvNY4mvIwyDlU55RlHGC4vWcoYrpW3uuz1S667VvGGThQB8WXL85VW3nx0kvzcVvSTitSW3RZhsmKGLGMSg_LYLnBO2R-BBQ4IeFQXzs9Os645rrRIH9w==',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFTCtYmDRH8kyG0WDZi3easTx1HsxXtqGc5-BaudPAdFfxHTjeA9gBtBEof_LRBI9YG7HgiUb770WnuCuxpMW9I5JAi4vMLaYotIai5nvx_R1qXIdRu9ahOorvPry7iCgxU1ZHrc_-VxIJ1VMgOlcgR2LNuOkh7jT73sFQGWi4CtUPQJPlHn3PMrEEXCQ=='],
   'Confidence': 1.0},
  {'Name': 'SQL Server 2016',
   'Summary': 'SQL Server 2016 follows a Fixed Lifecycle Policy, with Mainstream Support ending on July 13, 2021, and Extended Support, which is the official End-of-Support (EOS) date, ending on July 14, 2026.',
   'Hardware/Software': 'Software',
   'Support Model': 'Fixed',
   'EOS Date': '2026-07-14',
   'Support Tiers': [{'Tier': 'Mainstream Support', 'EndDate': '2021-07-13'},
    {'Tier': 'Extended Support', 'EndDate': '2026-07-14'}],
   'Source URLs': ['https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQElom5C-cQajVG_W5hrR99sY471yfcys273HZrjWMbYU4bFqKJRx6HeVN9o-XgxvUMcSYAK-2Waru47HG4ac6ZJaC9iuvVCNQMOTdZ849-XN7ixQWcnPxoJYbB7jfShouec-uI0xuoJWNqApKN_ZC8cDgFk-nuHAEfkOhWPrg==',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEzCR2ezeJ_yUgfpj7URAS0n-I8dtPPW270agcf6GODqb_LEYJ-1TgTJd-8WpGlMsdqIP9zl7H379_0ziBvltdXTI0KXi-tILjDaOGYi_tbwUXc2ukexSErLOgTe27ujaLdY9IzLIIBdyAdWqbV04Y=',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQELya0av2AHzgQ31kjANryZIrN7RgA5bnHWAYuj47ESMA8vQtiL131X6Ppis6yQLqS9gnoaK0ZzEhy5S2JvQwKrlFbyVAyWeCqpicIlclo9FpDo5C6WguO0ofQ4vAlqWhm8aEKDZSeMhO_RqPXa-ErtbQiV93jLsQjNm9KbqvzYaw==',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFo6h6C_Ge3RXQhP299jcBDAw89WMEnfdbS51NlooS8EjrJkbZyVAJyAt_db13zIqqg6CzsU7Rs6_DSbXC6GUngTk1_9KKJDV5MW8dg5gQq8far4HfiObzS68RXug8=',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHSW1_ph5vsUayji5NPXogMTsNs_-eWpIXXf29Muk9av5Lfu3j2283iq-MrGe-fW7XU0oLqOkHf3XdNS3FcBCQOy54AuzNh-7AWYmMm9Do5VdIcjqye4jGT8lYv33tfskzzJd_S4trxrxatHua3sUkd2mOsv4CWeHHlL7Ir2O-k',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHcTgEp5DIF_04fKe0FzXeGGu_kFKBO3BrJscmpr8md7JKZnypJ8o_kqoaE3YsnbBrRsNsbx_sLc5LsUSo1VkaGhF5gC1wQiN9MA6bRsQfF-lxdgBmyJNrB6FH4d-r4dnQvnuaIqNd6oNuRguPr1OdBWVkQ',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFUTjk9PjpN7efDV28rSGYrvI5gMerzYntPhPz9g1BN3mGxyjwPtiURgFKBQ8JuSW0nky5nJGg72oTedqQAfrO3LtX6yrlU1jRqb2CQ8nFxVSKm9boex4ARDO1rjM_oJWM=',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHhVTUWgnoz4YCBX6l_IH8V9vrIV_8izufFdOzyGCstQbAQV-N2W5Kmr_NDV0upjZYoEyFPAaMSTEAzanJo8TqL-_oaVgjeABWR1985Nm59bWH1InxSiQwmhJr254ulYggMHJfFIUDUFXzi5FqhwUkq_AiRycvy_BvmaAKsB7lcs3TVbyi--j3AVHeCE6SLpGfhwaP2',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEOsweOKOvKDShb-WEpvpR2gra--8ooSNhiVCunvbKhX99_Eq_FJeJDZhuiJpIK7nJ7YCTrVaA4CZaIuhc8DziIyzD1P_v5s7r9rvkvwJulxjUTU35t6QxMMZed03Qtl2kFFDXVXWxS4eqagpaCNkwZ7B-wzVcI01eYiKvSkJtWgA=',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFnOdONtBOuMNwNzwNeoLSBN6SkYuaBKbRZ6dU4EgPvk4vsSZk40g0hNgE-UlC9p5Dbik5rodHbhzGckcY4Cgf9MwWkVuQPfhy0915tzuCrDklAFcTWOHFzaAueN7sqf27twArZTmc2enX-3kkF6kjMLd5dRfQPUicVkQ6nlkyETQ7B_s5kwG==',
    'https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEByn_QFKtDoThOikqHzV8Rm9X1bHqlXlz2oG5talW-BtW7qdamQGUrSpAJ374rNjjBPL0Z-09fZyFtX_WkXOVIjbq5y3VtyXotM4gik_Ygd2lDS5VRJNdNkhBdRNMApigK0GTBGLI='],
   'Confidence': 1.0}],
 [])

In [80]:
def processing_tiers(df):
    df = pd.DataFrame(df)
    expl = df.explode('Support Tiers').reset_index(drop=True)
    tiers_df = pd.json_normalize(expl['Support Tiers'])
    final_df = expl.drop(columns=['Support Tiers']).join(tiers_df)
    return final_df

df_to_csv = processing_tiers(results[0])
df_to_csv['Source URLs'] = df_to_csv['Source URLs'].str.join(',')
df_to_csv.to_csv('omnii_output.csv', index=False)

In [83]:
df_to_csv

,Name,Summary,Hardware/Software,Support Model,EOS Date,Source URLs,Confidence,Tier,EndDate
0,7-Zip 19.00,"7-Zip operates on a rolling support model, mea...",Software,Rolling,None,"https://www.7-zip.org/support.html,https://sou...",1.0,NaN,NaN
1,Google Chrome 115.0.5790.102,Google Chrome operates on a rapid release cycl...,Software,Rolling,None,https://chromium.googlesource.com/chromium/src...,1.0,NaN,NaN
2,Splunk Universal Forwarder 9.0.2,Splunk Universal Forwarder versions 7.0 and on...,Software,Version-Based,2027-06-14,https://vertexaisearch.cloud.google.com/ground...,1.0,Mainstream Support,2024-06-14
3,Splunk Universal Forwarder 9.0.2,Splunk Universal Forwarder versions 7.0 and on...,Software,Version-Based,2027-06-14,https://vertexaisearch.cloud.google.com/ground...,1.0,Limited Support (P3 level),2027-06-14
4,Windows Server 2016,Windows Server 2016 follows a Fixed Lifecycle ...,Software,Fixed,2027-01-12,https://vertexaisearch.cloud.google.com/ground...,1.0,Mainstream Support,2022-01-11
5,Windows Server 2016,Windows Server 2016 follows a Fixed Lifecycle ...,Software,Fixed,2027-01-12,https://vertexaisearch.cloud.google.com/ground...,1.0,Extended Support,2027-01-12
6,SQL Server 2016,SQL Server 2016 follows a Fixed Lifecycle Poli...,Software,Fixed,2026-07-14,https://vertexaisearch.cloud.google.com/ground...,1.0,Mainstream Support,2021-07-13
7,SQL Server 2016,SQL Server 2016 follows a Fixed Lifecycle Poli...,Software,Fixed,2026-07-14,https://vertexaisearch.cloud.google.com/ground...,1.0,Extended Support,2026-07-14

### Plot

In [ ]:
tm = time.time()
time.sleep(1)
tm2 = time.time()- tm
# round to 2 decimal points

Time taken: 1.00 seconds

In [137]:
#df to csv

omnii_eos_sw = pd.read_csv('omnii_eos.csv')
omnii_eos_sw.head(5)

,Name,Summary,Hardware/Software,EOS Date,Source URLs,Confidence
0,Product Not Specified,No End-of-Support (EOS) date could be determin...,Software,No EOS found,[],0.0
1,.NET Framework 4.8.1,The .NET Framework 4.8.1 is a software compone...,Software,No specific end date (tied to Windows OS lifec...,['https://learn.microsoft.com/en-us/lifecycle/...,1.0
2,7-Zip 19.00,"7-Zip, as open-source software, does not have ...",Software,No EOS found,"['https://www.7-zip.org/support.html', 'https:...",1.0
3,Google Chrome 115.0.5790.102,Google Chrome 115.0.5790.102 reached its end-o...,Software,2023-08-15,['https://chromereleases.googleblog.com/2023/0...,1.0
4,Splunk Universal Forwarder 9.0.2,"Splunk Universal Forwarder 9.0.2, as part of t...",Software,2027-06-14,['https://vertexaisearch.cloud.google.com/grou...,1.0

In [1]:
import pandas as pd
import numpy as np # Used for representing null values

# Your list of JSON objects from the API/assistant
data = [
    {
      "Name": "Windows Server 2022",
      "Support Model": "Fixed",
      "EOS Date": "2031-10-14",
      "Support Tiers": [
          {"Tier": "Mainstream Support", "EndDate": "2026-10-13"},
          {"Tier": "Extended Support", "EndDate": "2031-10-14"}
      ]
    },
    {
      "Name": "Ubuntu 22.04 LTS",
      "Support Model": "Fixed",
      "EOS Date": "2032-04-30",
      "Support Tiers": [
          {"Tier": "Standard Security", "EndDate": "2027-04-30"},
          {"Tier": "Extended Security Maintenance (ESM)", "EndDate": "2032-04-30"}
      ]
    },
    {
      "Name": "Google Chrome",
      "Support Model": "Rolling",
      "EOS Date": None,
      "Support Tiers": [] # No fixed tiers
    }
]

# 1. Create the initial DataFrame
df = pd.DataFrame(data)

# 2. Explode the 'Support Tiers' column to create separate rows
#    Products with no tiers (like Chrome) will result in a row with NaN
df_exploded = df.explode('Support Tiers').reset_index(drop=True)

# 3. Normalize the 'Support Tiers' column (which now contains dictionaries)
#    and join it back to the main data
tiers_df = pd.json_normalize(df_exploded['Support Tiers'])
final_df = df_exploded.drop(columns=['Support Tiers']).join(tiers_df)

# Optional: Convert date strings to datetime objects for calculations
final_df['EOS Date'] = pd.to_datetime(final_df['EOS Date'])
final_df['EndDate'] = pd.to_datetime(final_df['EndDate'])

print(final_df)

                  Name Support Model   EOS Date  \
0  Windows Server 2022         Fixed 2031-10-14
1  Windows Server 2022         Fixed 2031-10-14
2     Ubuntu 22.04 LTS         Fixed 2032-04-30
3     Ubuntu 22.04 LTS         Fixed 2032-04-30
4        Google Chrome       Rolling        NaT

                                  Tier    EndDate
0                   Mainstream Support 2026-10-13
1                     Extended Support 2031-10-14
2                    Standard Security 2027-04-30
3  Extended Security Maintenance (ESM) 2032-04-30
4                                  NaN        NaT

In [2]:

final_df

,Name,Support Model,EOS Date,Tier,EndDate
0,Windows Server 2022,Fixed,2031-10-14,Mainstream Support,2026-10-13
1,Windows Server 2022,Fixed,2031-10-14,Extended Support,2031-10-14
2,Ubuntu 22.04 LTS,Fixed,2032-04-30,Standard Security,2027-04-30
3,Ubuntu 22.04 LTS,Fixed,2032-04-30,Extended Security Maintenance (ESM),2032-04-30
4,Google Chrome,Rolling,NaT,NaN,NaT